### ISSUE TITLE
jdk-11 and jdk-12 do not build on Solaris 11.4 with Solaris Studio 12.4

### ISSUE THREAD

**Issue by gco** [oracle/oraclesolaris-contrib#8]
Using Solaris Studio from https://pkg.oracle.com/solarisstudio/release/, jdk-11 and jdk-12 fail to build due to compiler errors in libharfbuzz.

The patch at https://gist.github.com/ellisvelo/8cb7290a8d6e67de8cf4ba99ffce31df works around it.

**Comment by psumbera** [comment]
What is your S11.4 version?

The script was testeed with recent SRU (SRU42). Note that there is also Oracle Solaris 11.4.42 CBE reslease which can be used if you don't have recent SRU (https://www.oracle.com/solaris/solaris11/downloads/solaris-downloads.html).

**Comment by psumbera** [comment]
Ok, maybe I'm using newer compiler version...

**Comment by gco** [comment]
Yes, I believe it's the compiler.

**Comment by psumbera** [comment]
Thank you for providing the fix!
